import React from 'react';
import { useSakhi } from '../context/SakhiContext';
import {
  X,
  ShieldCheck,
  Lock,
  Heart,
  AlertTriangle,
  FileText,
  PhoneCall,
  CheckCircle2
} from 'lucide-react';

export const PrivacyTermsModal: React.FC = () => {
  const { privacyModalOpen, setPrivacyModalOpen } = useSakhi();

  if (!privacyModalOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white rounded-3xl max-w-2xl w-full p-6 sm:p-8 border border-rose-100 shadow-2xl space-y-6 my-8 animate-fadeIn max-h-[90vh] overflow-y-auto">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 border-b border-rose-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-purple-50 border border-purple-100 flex items-center justify-center text-purple-600">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <div>
              <h2 className="font-display text-lg sm:text-xl font-bold text-rose-950">
                Privacy Policy, Terms & Medical Disclaimer
              </h2>
              <p className="text-[11px] text-stone-500">Sakhi Care Trust Commitment</p>
            </div>
          </div>

          <button
            onClick={() => setPrivacyModalOpen(false)}
            className="p-1.5 rounded-full hover:bg-stone-100 text-stone-400 hover:text-stone-700"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-6 text-xs sm:text-sm text-stone-600 leading-relaxed">
          
          {/* Critical Clinical Disclaimer Section */}
          <div className="p-4 rounded-2xl bg-rose-50/80 border border-rose-200 text-rose-950 space-y-2">
            <div className="flex items-center gap-2 font-bold text-rose-900 text-xs uppercase tracking-wide">
              <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0" />
              <span>Important Medical Disclaimer</span>
            </div>
            <p className="text-xs text-rose-900/90 leading-relaxed">
              <strong>Sakhi Care is a personal wellness, lifestyle, and menstrual cycle tracking platform.</strong> The predictions, fertile window estimations, symptom logs, and pregnancy week descriptions generated by this software are provided strictly for educational and self-awareness purposes.
            </p>
            <p className="text-xs text-rose-900/90 leading-relaxed">
              Sakhi Care does <strong>not</strong> provide medical diagnoses, clinical triage, or contraception guarantees. Automated insights do not replace the personalized judgment, examination, or care of an OB/GYN, midwife, physician, or qualified healthcare professional.
            </p>
          </div>

          {/* Emergency Helpline Note */}
          <div className="p-4 rounded-2xl bg-amber-50/80 border border-amber-200 text-amber-950 space-y-1">
            <div className="flex items-center gap-2 font-bold text-xs uppercase tracking-wide text-amber-900">
              <PhoneCall className="w-4 h-4 text-amber-700 shrink-0" />
              <span>Emergency Guidance</span>
            </div>
            <p className="text-xs text-amber-900">
              If you are experiencing severe lower abdominal pain, sudden fainting, heavy abnormal hemorrhaging, acute pregnancy complications, or mental health emergencies, please contact your local emergency services (e.g., 911, 112, or local women's hospital emergency hotline) immediately.
            </p>
          </div>

          {/* Privacy & Zero-Data-Selling Policy */}
          <div className="space-y-3">
            <h3 className="font-display text-base font-bold text-rose-950 flex items-center gap-2">
              <Lock className="w-4 h-4 text-emerald-600" />
              <span>Your Data Privacy is Sacred</span>
            </h3>

            <ul className="space-y-2 text-xs">
              <li className="flex items-start gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                <span><strong>No Public Exposure:</strong> Your menstrual logs, pregnancy records, and intimate moods are never published, indexed by search engines, or made visible to others.</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                <span><strong>Zero Data Brokerage:</strong> We never sell, rent, or broker your personal health details to advertising networks or third-party insurers.</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                <span><strong>Total Data Portability:</strong> You can export your full health history at any time as an encrypted JSON backup or wipe it completely with one click.</span>
              </li>
            </ul>
          </div>

          {/* Terms of Service */}
          <div className="space-y-2 pt-2 border-t border-stone-100 text-xs text-stone-500">
            <h4 className="font-bold text-stone-700">Terms of Use</h4>
            <p>
              By using Sakhi Care, you acknowledge that our cycle predictions are based on statistical mathematical averages and that natural human biological cycles fluctuate due to stress, illness, hormones, and lifestyle factors.
            </p>
            <p>
              Sakhi Care is designed with love, dignity, and empowerment for women everywhere.
            </p>
          </div>

        </div>

        {/* Action Button */}
        <div className="pt-3 border-t border-stone-100 flex justify-end">
          <button
            onClick={() => setPrivacyModalOpen(false)}
            className="px-6 py-2 rounded-full text-xs font-semibold text-white bg-rose-500 hover:bg-rose-600 shadow-xs"
          >
            I Understand & Agree
          </button>
        </div>

      </div>
    </div>
  );
};
